import { ServerRoute } from "./router.js";

export function importById(id: string): Promise<any> {
  throw new Error(
    "This file should not be included in the bundle output.\n" +
      "It is generated by the bundler and should only be imported in code that runs in the browser."
  );
}

export interface BrowserManifestEntry {
  module: string;
  imports: string[];
}

export type BrowserManifest = Record<string, BrowserManifestEntry>;

export declare const browserManifest: BrowserManifest;

export declare const routes: ServerRoute[];
